site_name: resty-stone
pages:
- ['index.md', Home]
- ['tutorial/quickstart.md', 'Tutorial', 'Quickstart']
site_url: http://shlomiassaf.github.io/resty-stone
site_dir: sites
repo_url: https://github.com/shlomiassaf/resty-stone/
site_description: Rest API toolkit for KeystoneJS framework
site_author: Shlomi Assaf